In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans:- 
Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, while array_list is a NumPy array.'''
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [5]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
#arra_list.'''

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
'''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list '''

'''Ans:- Yes, there will be a difference in the data types of the elements present in both the variables, list_ and array_list, after the modification.

Here's the code to print the data types of each element present in both the original list_ and the modified array_list after changing the dtype to int:'''




In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''

# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.'''

# Create a 3x3 matrix containing zeros
zeros_array = np.zeros((3, 3))

print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?'''

identity_matrix = np.identity(5)

print("Identity matrix of shape (5, 5):")
print(identity_matrix)

Identity matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
